// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: test/member/member.proto

package member

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MemberSeviceClient is the client API for MemberSevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemberSeviceClient interface {
	GetList(ctx context.Context, in *IDs, opts ...grpc.CallOption) (*MemberList, error)
}

type memberSeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberSeviceClient(cc grpc.ClientConnInterface) MemberSeviceClient {
	return &memberSeviceClient{cc}
}

func (c *memberSeviceClient) GetList(ctx context.Context, in *IDs, opts ...grpc.CallOption) (*MemberList, error) {
	out := new(MemberList)
	err := c.cc.Invoke(ctx, "/test.member.MemberSevice/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberSeviceServer is the server API for MemberSevice service.
// All implementations must embed UnimplementedMemberSeviceServer
// for forward compatibility
type MemberSeviceServer interface {
	GetList(context.Context, *IDs) (*MemberList, error)
	mustEmbedUnimplementedMemberSeviceServer()
}

// UnimplementedMemberSeviceServer must be embedded to have forward compatible implementations.
type UnimplementedMemberSeviceServer struct {
}

func (UnimplementedMemberSeviceServer) GetList(context.Context, *IDs) (*MemberList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedMemberSeviceServer) mustEmbedUnimplementedMemberSeviceServer() {}

// UnsafeMemberSeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberSeviceServer will
// result in compilation errors.
type UnsafeMemberSeviceServer interface {
	mustEmbedUnimplementedMemberSeviceServer()
}

func RegisterMemberSeviceServer(s grpc.ServiceRegistrar, srv MemberSeviceServer) {
	s.RegisterService(&MemberSevice_ServiceDesc, srv)
}

func _MemberSevice_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberSeviceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.member.MemberSevice/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberSeviceServer).GetList(ctx, req.(*IDs))
	}
	return interceptor(ctx, in, info, handler)
}

// MemberSevice_ServiceDesc is the grpc.ServiceDesc for MemberSevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemberSevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.member.MemberSevice",
	HandlerType: (*MemberSeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _MemberSevice_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/member/member.proto",
}
